# Generated by Django 5.2.4 on 2025-09-04 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_habit_habitrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitTrackingMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months_tracked', to='to_do_list.habit')),
            ],
            options={
                'unique_together': {('habit', 'year', 'month')},
            },
        ),
    ]
